// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskManagementAPI.Data;

#nullable disable

namespace Risk_Intake___Assessment_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521165157_AddControlsTable")]
    partial class AddControlsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiskManagementAPI.Models.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EffectivenessScore")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Perform comprehensive security audits of all vendors handling sensitive data",
                            EffectivenessScore = 4,
                            RiskId = 1,
                            Title = "Quarterly Vendor Security Audit",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Include right-to-audit and termination for security breach clauses in all vendor contracts",
                            EffectivenessScore = 3,
                            RiskId = 1,
                            Title = "Vendor Contract Termination Clause",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Maintain at least two qualified suppliers for all critical components",
                            EffectivenessScore = 3,
                            RiskId = 2,
                            Title = "Multi-Source Procurement Strategy",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Automated hedging for foreign currency exposure above $5M",
                            EffectivenessScore = 4,
                            RiskId = 3,
                            Title = "Real-time Currency Hedging Program",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Daily monitoring of currency exposure with alerts for thresholds",
                            EffectivenessScore = 4,
                            RiskId = 3,
                            Title = "Weekly Currency Position Monitoring",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Establish strategic partnerships with local firms in target markets",
                            EffectivenessScore = 3,
                            RiskId = 4,
                            Title = "Local Partnership Program",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Real-time threat detection and response system",
                            EffectivenessScore = 4,
                            RiskId = 8,
                            Title = "24/7 Security Monitoring",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Daily encrypted backups stored offline for ransomware recovery",
                            EffectivenessScore = 3,
                            RiskId = 8,
                            Title = "Offline Backups",
                            Type = 2
                        });
                });

            modelBuilder.Entity("RiskManagementAPI.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<int>("LikelihoodScore")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Risk of sensitive customer data being exposed through third-party vendor",
                            ImpactScore = 4,
                            LikelihoodScore = 3,
                            OwnerId = "owner-001",
                            Status = 2,
                            Title = "Vendor Data Breach"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CreatedAt = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Key microchip supplier could face production delays",
                            ImpactScore = 5,
                            LikelihoodScore = 2,
                            OwnerId = "owner-002",
                            Status = 1,
                            Title = "Supply Chain Disruption"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy exposure to EUR/USD exchange rate fluctuations",
                            ImpactScore = 3,
                            LikelihoodScore = 4,
                            OwnerId = "owner-003",
                            Status = 0,
                            Title = "Currency Exchange Rate Volatility"
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            CreatedAt = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expanding into Japan and South Korea markets",
                            ImpactScore = 4,
                            LikelihoodScore = 3,
                            OwnerId = "owner-001",
                            Status = 2,
                            Title = "Asia-Pacific Market Entry Failure"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Potential non-compliance with GDPR requirements",
                            ImpactScore = 5,
                            LikelihoodScore = 2,
                            OwnerId = "owner-004",
                            Status = 3,
                            Title = "GDPR Compliance Gaps"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            CreatedAt = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Senior architect has critical knowledge of legacy systems",
                            ImpactScore = 4,
                            LikelihoodScore = 3,
                            OwnerId = "owner-002",
                            Status = 1,
                            Title = "Loss of Key Technical Leadership"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "$50M in variable-rate debt tied to SOFR",
                            ImpactScore = 3,
                            LikelihoodScore = 4,
                            OwnerId = "owner-005",
                            Status = 0,
                            Title = "Rising Interest Rates Impact on Loans"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            CreatedAt = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Increasing ransomware attacks in the industry",
                            ImpactScore = 5,
                            LikelihoodScore = 3,
                            OwnerId = "owner-001",
                            Status = 2,
                            Title = "Ransomware Attack on Production Systems"
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            CreatedAt = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New startup with AI-driven solution could disrupt our pricing model",
                            ImpactScore = 4,
                            LikelihoodScore = 4,
                            OwnerId = "owner-003",
                            Status = 0,
                            Title = "AI-Powered Competitor Entering Market"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            CreatedAt = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Proposed legislation would require 40% reduction in carbon emissions",
                            ImpactScore = 4,
                            LikelihoodScore = 3,
                            OwnerId = "owner-004",
                            Status = 1,
                            Title = "New Carbon Emission Regulations"
                        });
                });

            modelBuilder.Entity("RiskManagementAPI.Models.Control", b =>
                {
                    b.HasOne("RiskManagementAPI.Models.Risk", "Risk")
                        .WithMany("Controls")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("RiskManagementAPI.Models.Risk", b =>
                {
                    b.Navigation("Controls");
                });
#pragma warning restore 612, 618
        }
    }
}
